

// --- CORE IDENTITIES ---

export enum UserArchetype {
  EXPLORADOR = 'EXPLORADOR',
  CONSTRUCTOR = 'CONSTRUCTOR',
  ESENCIALISTA = 'ESENCIALISTA'
}

// Niveles de Suscripción (The 4 Tiers)
export enum SubscriptionTier {
  FREE = 'INVITADO',        // Nivel 1: Información y Alertas calculadas
  BASIC = 'ASISTENTE',      // Nivel 2: Gestión Básica
  PRO = 'MAYORDOMO',        // Nivel 3: Ejecución y Trámites
  VIP = 'GOBERNANTE'        // Nivel 4: Proactividad Total y Gestión de Terceros
}

// --- CONTEXTO GLOBAL & JURISDICCIÓN (New) ---

export type JurisdictionCode = 'ES' | 'US' | 'UK' | 'TH' | 'GLOBAL';
export type LifeContextType = 'RESIDENT' | 'NOMAD' | 'EXPAT' | 'CITIZEN';

export interface Jurisdiction {
  code: JurisdictionCode;
  name: string;
  region?: string; // Comunidad Autónoma / Estado
  taxResidency: boolean;
}

// --- OBLIGATIONS & INFERENCE (AI Engine) ---

export enum ObligationCategory {
  IDENTITY = 'IDENTITY',
  TAX = 'TAX',
  HEALTH = 'HEALTH',
  ASSET = 'ASSET',
  HOUSING = 'HOUSING',
  LEGAL = 'LEGAL'
}

export enum ObligationStatus {
  MISSING = 'MISSING',
  WARNING = 'WARNING',
  OK = 'OK'
}

export interface LifeObligation {
  id: string;
  title: string;
  category: ObligationCategory;
  jurisdiction: string;
  status: ObligationStatus;
  metadata?: Record<string, any>;
  description?: string;
}

export interface LifeContext {
  currentJurisdiction: Jurisdiction;
  targetJurisdiction?: Jurisdiction; // Si hay transición en curso
  status: LifeContextType;
  isCouple: boolean;
  hasDependents: boolean;
  obligations?: LifeObligation[]; // Generated by InferenceEngine
}

// --- THE 5 PILLARS (Módulos) ---

export enum PillarId {
  CENTINELA = 'centinela',       // Legal/Admin
  PATRIMONIO = 'patrimonio',     // Hogar + Finanzas
  CONCIERGE = 'concierge',       // Ocio y Viajes
  VITAL = 'vital',               // Coach / Salud
  NUCLEO = 'nucleo'              // Familia / Logística
}

export interface PillarStatus {
  id: PillarId;
  name: string;
  description: string;
  isActive: boolean; // True si Tier >= Requerido
  isDegraded: boolean; // True si Tier OK pero Permiso Técnico OFF
  statusMessage: string; // Ej: "Esperando acceso a bancos" o "Operativo"
  alerts: number;
}

// --- PROTOCOLS & MISSIONS (Renamed from Mission) ---

export type ProtocolType = 'RELOCATION' | 'LEGAL_COMPLIANCE' | 'ASSET_ACQUISITION' | 'LIFE_EVENT';

export interface ProtocolItem {
  id: string;
  label: string; // "Baja Modelo 030 (Hacienda)"
  type: 'DOC' | 'ASSET' | 'TASK' | 'LEGAL';
  sourcePillar: PillarId;
  jurisdiction: JurisdictionCode; // "ES" o "TH"
  phase: 'EXIT' | 'ENTRY' | 'MAINTENANCE'; // Para transiciones
  isReady: boolean; // Si la IA ya ha hecho el trabajo de preparación
  notes?: string;
  actionUrl?: string; // Deep link para ejecutar
  
  // GOLDEN RULE: FINANCIAL SECURITY
  requiresApproval?: boolean; // True si implica gasto o compromiso legal
  cost?: number; // Importe a aprobar
  currency?: string; // Moneda
  approved?: boolean; // True si el usuario ya ha firmado
}

export interface ProtocolContext {
  origin?: string;
  destination?: string;
  effectiveDate: Date;
  criticalAlert?: string; // "Requiere Visado antes del vuelo"
  weatherCondition?: string;
  trafficStatus?: string;
}

export type MissionContext = ProtocolContext;

export interface Mission { // Mantengo el nombre Mission para compatibilidad UI, pero conceptualmente es un Protocolo
  id: string;
  title: string; // "Protocolo: Reubicación Internacional"
  date: Date;
  type: ProtocolType | string;
  context: ProtocolContext | any; 
  checklist: ProtocolItem[]; 
}

// --- PERMISSION MATRIX (RBAC) ---
export type PermissionCategory = 'SYSTEMIC' | 'FUNCTIONAL';
export type AutomationLevel = 'manual' | 'semi' | 'full';

export interface TechnicalPermission {
  id: string;
  label: string;
  description: string;
  category: PermissionCategory;
  relatedPillar: PillarId;
  requiredForFullFeature: boolean;
  minTier?: SubscriptionTier;
}

export interface FeatureConfig {
  access: boolean;
  limit: number | null;
  automation_level: AutomationLevel;
  behavior: string;
}

export interface FeatureMatrixItem {
  id: string;
  pillarId: PillarId;
  name: string;
  description: string;
  requiredPermissionId?: string;
  tiers: Record<SubscriptionTier, FeatureConfig>;
}

// --- SIXTH SENSE (New Module) ---

export type OpportunityType = 'SAVING' | 'NETWORKING' | 'LOGISTICS' | 'NOSTALGIA';

export interface SixthSenseOpportunity {
  id: string;
  type: OpportunityType;
  title: string;
  description: string;
  impactLabel: string; // "+150€/mes", "Conexión Clave"
  actionLabel: string;
}

// --- DASHBOARD ITEMS (Generative) ---

export type DashboardItemType = 'NOSTALGIA' | 'DECISION' | 'ZEN' | 'SIXTH_SENSE';

export interface DashboardItem {
  id: string;
  type: DashboardItemType;
  title: string;
  description: string;
  pillarId?: PillarId;
  isLocked?: boolean;
  metadata?: any;
  priority: number; // 0-100 (Higher shows first)
  
  // New: Permission Linking
  requiredPermission?: string; // ID of the technical permission needed (e.g., 'sys_email_read')

  // Specific for Sixth Sense Wrapper
  opportunities?: SixthSenseOpportunity[];
}

// --- UX / UI PREFERENCES ---

export type ThemePreference = 'AUTO' | 'LIGHT' | 'DARK';

// VISUAL ATMOSPHERE ENGINE
export type VisualThemeType = 'PRESET' | 'CUSTOM';

export interface AppThemeConfig {
  type: VisualThemeType;
  value: string; // ID del Preset (ej: 'ROYAL') o Base64 Data URI de la imagen
}

export interface DashboardConfig {
  pillarOrder: PillarId[];
  hiddenPillars: PillarId[];
}

// --- SUPPORT & MONITORING (New) ---

export interface SupportUserStatus {
    uid: string;
    email: string;
    tier: SubscriptionTier;
    systemHealth: 'OPTIMAL' | 'DEGRADED' | 'CRITICAL'; // Connection status (APIs, etc)
    fraudRisk: 'LOW' | 'MEDIUM' | 'HIGH'; // Concurrent logins, failed payments
    aiTokensUsed: number; // 0-100% of quota
    lastActive: Date;
}

// --- AUDIT & LEGAL (New Firestore Collections) ---

export interface AuditLog {
  id?: string;
  timestamp: Date; // Firestore Timestamp
  action: string; // "EXECUTE_TRANSFER", "SIGN_DOCUMENT"
  authorizedBy: 'USER' | 'AI';
  details: Record<string, any>;
  ipAddress?: string;
}

export interface LegalMandate {
  id?: string;
  title: string; // "Poder Notarial General"
  grantedTo: 'AI_AGENT';
  scope: string[]; // ['TAX_FILING', 'UTILITY_SWITCHING']
  signedAt: Date;
  expiresAt: Date;
  status: 'ACTIVE' | 'REVOKED' | 'EXPIRED';
  signatureHash: string; // Simulacro de firma criptográfica
}

// --- DATA DICTIONARY (Universal Categories) ---

// 1. Centinela (Global Identity & Legal)
export interface CentinelaData {
  identity: {
    passport?: { number: string; expiry: Date; issuer: string };
    nationalId?: { number: string; expiry: Date; name: string }; // DNI/GreenCard/ThaiID
    visas: { type: string; expiry: Date; jurisdiction: string }[];
    residencyPermit?: { number: string; status: string };
  };
  fiscal: {
    taxId: string; // NIF/SSN
    taxResidency: JurisdictionCode;
    obligations: { name: string; dueDate: Date; status: 'PENDING' | 'FILED' }[]; // IRPF, Modelo 720
  };
  civics: {
    votingRegistry: string;
    censusStatus: 'ACTIVE' | 'INACTIVE';
  };
}

// 2. Patrimonio (Universal Assets)
export interface PatrimonioData {
  utilities: { 
    type: 'ELECTRICITY' | 'WATER' | 'INTERNET'; 
    provider: string; 
    contractId: string; 
    jurisdiction: JurisdictionCode; 
    status: 'ACTIVE' | 'CANCELLED';
  }[];
  realEstate: {
    type: 'OWNED' | 'RENTED';
    address: string;
    jurisdiction: JurisdictionCode;
    contracts: { type: 'DEED' | 'LEASE'; expiry?: Date }[];
  }[];
  banking: {
    globalBalance: number;
    currencyDistribution: Record<string, number>; // EUR: 80%, USD: 20%
  }
}

// ... Otros tipos auxiliares ...
export interface UserProfile {
  uid: string;
  email: string;
  name: string;
  role?: 'ADMIN' | 'USER'; // NEW: RBAC Role
  age: number;
  birthDate?: string; // ISO Date YYYY-MM-DD
  gender: string;
  
  // Professional
  occupation: string;
  sector?: string;
  workModality?: 'REMOTE' | 'HYBRID' | 'ONSITE';

  // Context
  maritalStatus?: 'SINGLE' | 'PARTNER' | 'MARRIED' | 'DIVORCED';
  zipCode?: string;

  archetype: UserArchetype;
  subscriptionTier: SubscriptionTier;
  grantedPermissions: string[];
  setupCompleted: boolean;
  
  // New Life Context
  lifeContext?: LifeContext;
  
  // UX Preferences
  themePreference?: ThemePreference;
  themeConfig?: AppThemeConfig; // NEW: Visual Atmosphere settings
  dashboardConfig?: DashboardConfig;
  
  // Security
  mfaEnabled?: boolean;
}

export interface VaultItem {
  id: string;
  type: 'BANK_TOKEN' | 'DIGITAL_CERT' | 'DEHU_CREDS' | 'HEALTH_TOKEN';
  encryptedData: string;
  iv: string; // Initialization Vector
  updatedAt: Date;
}

export interface Attachment {
  type: 'image' | 'video' | 'file';
  mimeType: string;
  data: string;
  name: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
  attachments?: Attachment[];
}

export type CapabilityStatus = 'GRANTED' | 'BLOCKED_TIER' | 'BLOCKED_PERMISSION' | 'DEGRADED';

export enum Owner {
  AI = 'AI',
  USER = 'USER'
}

export interface HouseSector {
  id: string;
  name: string;
  type: string;
  efficiency: number; 
  status: 'OPTIMAL' | 'ATTENTION' | 'CRITICAL';
  description: string;
  owner: Owner;
}

export interface Insight {
  id: string;
  title: string;
  description: string;
  impact: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  actionable: boolean;
  date?: Date;
}

export interface MacroContextEvent {
  id: string;
  source: string;
  title: string;
  description: string;
  timestamp: Date;
  riskLevel: 'CRITICAL' | 'HIGH' | 'MODERATE' | 'LOW';
}

export interface PermissionItem {
  id: string;
  label: string;
  defaultEnabled: boolean;
  minTier?: SubscriptionTier;
}

export interface PermissionModule {
  id: string;
  title: string;
  permissions: PermissionItem[];
}

export interface LifeStageConfig {
  stageName: string;
  description: string;
  modules: PermissionModule[];
}

export interface PermissionProposal {
  id: string;
  relatedMacroEventId: string;
  title: string;
  targetModuleId: string;
  reasoning: string;
  proposedPermission: PermissionItem;
}